name: Sync Upstream

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/husamahmud/pstrack.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream main

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes to origin
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin main
