# name: CI

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   prettier:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '>=16'
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Install dependencies
#         run: pnpm install --strict-peer-dependencies=false
#       - name: Run Prettier
#         run: pnpm run prettier

#   eslint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '>=16'
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Install dependencies
#         run: pnpm install --strict-peer-dependencies=false
#       - name: Run ESLint
#         run: pnpm run lint

#   typecheck:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '>=16'
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Install dependencies
#         run: pnpm install --strict-peer-dependencies=false
#       - name: Run Typecheck
#         run: pnpm run typecheck

#   build:
#     runs-on: ubuntu-latest
#     needs: [typecheck]
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '>=16'
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Install dependencies
#         run: pnpm install --strict-peer-dependencies=false
#       - name: Run Build
#         run: pnpm run build
